### PR TITLE
Added rooms idea

### PR DESCRIPTION
**Pull request by jonathan-ostrander**
Bitch like my rooms.

### CODE REVIEW

**Comment by choochootrain** [comment]
:shit:

**Comment by choochootrain** [comment]
kill yourself github

**Comment by SharangP** [comment]
you broke it jon. spaces after dashes in lists.
fixed.

On Mon, Nov 2, 2015 at 11:28 PM, Jonathan Ostrander <
notifications@github.com> wrote:

> ## Bitch like my rooms.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/SharangP/ideas/pull/2
> Commit Summary
> - added rooms idea
> 
> File Changes
> - _M_ list.yaml https://github.com/SharangP/ideas/pull/2/files#diff-0
>   (7)
> 
> Patch Links:
> - https://github.com/SharangP/ideas/pull/2.patch
> - https://github.com/SharangP/ideas/pull/2.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SharangP/ideas/pull/2.

## 

Sharang Phadke
http://sharangphadke.me

**Comment by choochootrain** [comment]
autoaccept is best accept

**Pull request merged**
