### PR TITLE
spellcheck - very cool

### PR DESCRIPTION
**Pull request by luster**

### CODE REVIEW

**Review by jonathan-ostrander — APPROVED** [review]
LGTM

**Comment by choochootrain** [comment]
👎 this is not backwards compatible with ES8. i tried
```bash
$ npm install SharangP/ideas
-bash: npm: command not found
```

so i think we should revert this and add unit tests because it isn't webscale

**Comment by SharangP** [comment]
How bout some docker?

On Mar 20, 2017 11:53 PM, "Hurshal Patel" <notifications@github.com> wrote:

👎 this is not backwards compatible with ES8. i tried

$ npm install SharangP/ideas
-bash: npm: command not found

so i think we should revert this and add unit tests because it isn't
webscale

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/SharangP/ideas/pull/10#issuecomment-287969819>, or mute
the thread

**Comment by jonathan-ostrander** [comment]
:-1: also not compatible with docker either.

```
$ docker run -it SharangP/ideas
-docker: invalid reference format: repository name must be lowercase.
```

we need to refactor the entire repo from the ground up

**Comment by luster** [comment]
```bash
~/src/ideas(master ✔) python app.py
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    import yaml
ImportError: No module named yaml
```

we should roll a custom yaml parser in vanilla JS and remove dependencies

**Comment by jonathan-ostrander** [comment]
```
root@b34b28a03bd4:/# git clone https://github.com/SharangP/ideas.git
bash: git: command not found
```
Uh oh, we may want to use a custom VCS too.  Looks like we broke github.

**Pull request merged**
