### PR TITLE
HOT HOT HOT

### PR DESCRIPTION
**Pull request by jonathan-ostrander**

### CODE REVIEW

**Comment by choochootrain** [comment]
u should also remove `.gitignore` in this commit so u can ignore while u ignore ur ignored

**Comment by jonathan-ostrander** [comment]
Bullshit

**Comment by choochootrain** [comment]
there is no need for hostility. this is an open source project that we maintain in our free time. reopening due to tone

**Comment by choochootrain** [comment]
ay boi listen 2 me

**Comment by choochootrain** [comment]
k fine

**Pull request closed without merging**
